version: "3.3"

services:
  mongo1:
    image: mongo:7.0.1
    container_name: mongo1
    restart: always
    command: mongod --replSet jutopia-repl --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - ~/data/mongo/mongo1:/data/db
    networks:
      - jutopia-network

  mongo2:
    image: mongo:7.0.1
    container_name: mongo2
    restart: always
    command: mongod --replSet jutopia-repl --bind_ip_all --port 27018
    ports:
      - 27018:27018
    volumes:
      - ~/data/mongo/mongo2:/data/db
    networks:
      - jutopia-network

  mongo3:
    image: mongo:7.0.1
    container_name: mongo3
    restart: always
    command: mongod --replSet jutopia-repl --bind_ip_all --port 27019
    ports:
      - 27019:27019
    volumes:
      - ~/data/mongo/mongo3:/data/db
    networks:
      - jutopia-network

networks:
  jutopia-network:
    external: true